name: Report coverage
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: --label rabbitmq
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('buildout.cfg') }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v1
      with:
        path: eggs
        key: ${{ runner.os }}-eggs-${{ hashFiles('buildout.cfg') }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-eggs-


    - name: Install dependencies
      run: |
        pip install -U tox
    - name: Generate coverage report
      env:
        AMQP_RABBITMQCTL: docker exec $(docker ps -aqf "label=rabbitmq") rabbitmqctl
      run: |
        tox -e coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        env_vars: OS,PYTHON
        name: github actions coverage
        fail_ci_if_error: true
